version: "3"
services:
  backend:
    build: ./backend/project
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/project:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres1
    restart: always
    
  postgres:
    image: postgres:latest
    container_name: postgres_new
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend/notes-app
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    
      
 
 
